project:
  type: book

book:
  title: "Foundations of Vision (Version 1.1)"
  author: "Brian Wandell"
  date: "10/26/2024"
  chapters:
    - index.qmd
    - part: "Image Encoding"
      chapters:
       - part-1-image-encoding.qmd
       - chapter-2-image-formation.qmd
       - chapter-3-the-photoreceptor-mosaic.qmd
       - chapter-4-wavelength-encoding.qmd
    - part:  "Image Representation"
      chapters:
      - part-2-image-representation.qmd
      - chapter-5-the-retinal-representation.qmd
      - chapter-6-the-cortical-representation.qmd
      - chapter-7-pattern-sensitivity.qmd
      - chapter-8-multiresolution-image-representations.qmd
    - part: "Image Interpretation"
      chapters:
       - part-3-image-interpretation.qmd
       - chapter-9-color.qmd
       - chapter-10-motion-and-depth.qmd
       - chapter-11-seeing.qmd
    - references.qmd
    - part: "Appendix"
      chapters:
       - appendix.qmd
       - computational-examples.qmd
       - online-teaching-resources.qmd

bibliography: references.bib

crossref:
  chapters: true
  fig-prefix: "Figure"
  tbl-prefix: "Table"
  sec-prefix: "Section"
  
#  I am unsure about these formatting commands for the document.  Experimental.
format:
  html:
    theme: cosmo
    math: 
      number-sections: true
  pdf:
    documentclass: scrreprt
    toc: true
    toc-title: "Contents"
    toc-number-sections: true
    toc-number-depth: 2
    fig-caption: true
    number-sections: true
    number-depth: 2
    math:
      number-equations: true





